import Foundation

/// Pure functions that turn a JSON fixture into a Swift source string and
/// derive the matching filenames and type names. No I/O lives here, so the
/// renderer can be unit-tested without filesystem fixtures.
public enum WrapperRenderer {

    /// Build the Swift source for a `*+SmartAPI.swift` wrapper.
    ///
    /// - Parameters:
    ///   - typeName: Public enum name to declare (already PascalCase).
    ///   - sourceFile: Original `.smartapi.json` path, surfaced as a top-of-file comment so the
    ///     generated source traces back to its fixture.
    ///   - json: Raw JSON contents to inline as the `@SmartAPI(sample:)` argument.
    public static func renderSwiftWrapper(
        typeName: String,
        sourceFile: String,
        json: String
    ) -> String {
        // Pick a raw-string delimiter strong enough to survive any `"""<#×n>`
        // run in the JSON. Most JSON only needs `#"""..."""#`.
        let delimiterDepth = chooseDelimiter(for: json)
        let openDelimiter = String(repeating: "#", count: delimiterDepth) + "\"\"\""
        let closeDelimiter = "\"\"\"" + String(repeating: "#", count: delimiterDepth)
        let trimmedJSON = json.trimmingCharacters(in: .whitespacesAndNewlines)

        return """
        // AUTO-GENERATED by smartapi-bundle from \(sourceFile)
        // Do not edit by hand. Re-run `swift run smartapi-bundle` to refresh.

        import SmartAPI

        @SmartAPI(sample: \(openDelimiter)
        \(trimmedJSON)
        \(closeDelimiter))
        public enum \(typeName) {}
        """
    }

    /// Smallest delimiter depth where `"""<#×depth>` doesn't appear in the
    /// JSON. Lets us pick the right raw-string opener for any input.
    public static func chooseDelimiter(for json: String) -> Int {
        (1...).first { depth in
            !json.contains("\"\"\"" + String(repeating: "#", count: depth))
        } ?? 1
    }

    // MARK: - Name & path derivation

    /// `Path/To/foo.smartapi.json` → `Path/To/foo+SmartAPI.swift` (sibling file).
    public static func derivedSwiftPath(forJSONAt jsonPath: String) -> String {
        let directory = (jsonPath as NSString).deletingLastPathComponent
        let base = baseName(forJSONAt: jsonPath)
        return (directory as NSString).appendingPathComponent("\(base)+SmartAPI.swift")
    }

    /// `Path/To/foo_bar.smartapi.json` → `"FooBar"`.
    public static func derivedTypeName(forJSONAt jsonPath: String) -> String {
        pascalCase(baseName(forJSONAt: jsonPath))
    }

    /// Strip `".smartapi.json"` from the path's last component.
    public static func baseName(forJSONAt jsonPath: String) -> String {
        let file = (jsonPath as NSString).lastPathComponent
        if let range = file.range(of: ".smartapi.json", options: [.backwards]) {
            return String(file[..<range.lowerBound])
        }
        // Fallback for unexpected suffixes — strip up to two extensions.
        return ((file as NSString).deletingPathExtension as NSString).deletingPathExtension
    }

    /// Split on non-identifier characters and PascalCase each piece.
    public static func pascalCase(_ identifier: String) -> String {
        identifier
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map { String($0.prefix(1)).uppercased() + $0.dropFirst() }
            .joined()
    }
}
