// AUTO-GENERATED by smartapi-bundle from post.smartapi.json
// Do not edit by hand. Re-run `swift run smartapi-bundle` to refresh.

import SmartAPI

@SmartAPI(sample: #"""
{
  "id": 101,
  "title": "Welcome to SmartAPI",
  "body": "This is a long-form post body with multiple sentences that the macro should render as multi-line text. SmartAPI infers the type and picks the right widget automatically.",
  "author_name": "Ada Lovelace",
  "avatar_url": "https://i.pravatar.cc/150?u=ada",
  "is_pinned": true,
  "published_at": "2024-09-15T14:00:00Z",
  "tags": ["intro", "swift", "macros"]
}
"""#)
public enum Post {}