import Foundation
#if canImport(SwiftUI)
import SwiftUI
import Observation

// MARK: - Protocol

/// What `SmartPaginatedView` and other UI integrations need from a loader.
/// Any custom loader (a hand-rolled one not from `@SmartAPI`) can conform
/// and reuse the same SwiftUI machinery.
@MainActor
public protocol PaginatedLoaderProtocol: AnyObject {
    associatedtype Item: Identifiable & Hashable & Decodable & Sendable

    var items: [Item] { get }
    var hasMore: Bool { get }
    var isLoadingMore: Bool { get }
    var lastRefreshErrorDescription: String { get }
    var state: LoadState<[Item]> { get }

    /// Reset and fetch the first page.
    func load() async

    /// Append the next page. Must be a no-op when `!hasMore` or `isLoadingMore`.
    func loadMore() async

    /// Clear items + reset pagination state without fetching.
    func reset()
}

// MARK: - PaginatedLoader

/// Drives a `PaginationStrategy<Page, Item>` against a `SmartFetching`.
/// Holds the accumulated items, the current pagination state, and the
/// observable flags `SmartPaginatedView` reads.
///
/// Generated by `@SmartAPI(paginated: ...)` as `Posts.Loader`
/// (via a typealias to this concrete generic type). You can also
/// instantiate it manually for custom strategies.
@MainActor
@Observable
public final class PaginatedLoader<Page: Decodable & Sendable, Item: Decodable & Sendable & Identifiable & Hashable>: SmartLoaderProtocol, PaginatedLoaderProtocol {

    public typealias Value = [Item]

    public var state: LoadState<[Item]> = .idle
    public private(set) var items: [Item] = []
    public private(set) var hasMore: Bool = true
    public private(set) var isLoadingMore: Bool = false
    public private(set) var lastRefreshErrorDescription: String = ""

    public let baseQuery: SmartQuery
    public let strategy: PaginationStrategy<Page, Item>
    public let fetcher: any SmartFetching
    public let observer: any SmartAPIObserver
    public let typeName: String

    private var paginationState: PaginationStrategy<Page, Item>.State

    public init(
        baseQuery: SmartQuery,
        strategy: PaginationStrategy<Page, Item>,
        fetcher: any SmartFetching = SmartClient.shared,
        observer: any SmartAPIObserver = SmartAPILogger.shared,
        typeName: String = "PaginatedLoader"
    ) {
        self.baseQuery = baseQuery
        self.strategy = strategy
        self.fetcher = fetcher
        self.observer = observer
        self.typeName = typeName
        self.paginationState = strategy.initialState
    }

    /// Reset everything and fetch page 1. Replaces `items`.
    public func load() async {
        paginationState = strategy.initialState
        items = []
        hasMore = true
        state = .loading
        lastRefreshErrorDescription = ""
        await fetchOnePage()
    }

    /// Append the next page. No-ops while a fetch is in flight or when
    /// the strategy says there's nothing left.
    public func loadMore() async {
        guard hasMore, !isLoadingMore else { return }
        isLoadingMore = true
        await fetchOnePage()
        isLoadingMore = false
    }

    /// Clear accumulated items + pagination state. Doesn't fire a request.
    public func reset() {
        paginationState = strategy.initialState
        items = []
        hasMore = true
        state = .idle
        lastRefreshErrorDescription = ""
    }

    private func fetchOnePage() async {
        let extraQueryItems = strategy.queryItems(paginationState)
        let query = extraQueryItems.isEmpty
            ? baseQuery
            : baseQuery.appending(queryItems: extraQueryItems)
        let startedAt = Date()
        observer.loaderStarted(typeName: typeName, url: query.url)

        do {
            let page = try await fetcher.fetch(Page.self, via: query)
            guard !Task.isCancelled else { return }

            let outcome = strategy.advance(page, paginationState)
            paginationState = outcome.newState
            items.append(contentsOf: outcome.items)
            hasMore = outcome.newState.hasMore
            state = .loaded(items)
            lastRefreshErrorDescription = ""

            observer.loaderSucceeded(
                typeName: typeName,
                url: query.url,
                latency: Date().timeIntervalSince(startedAt)
            )
        } catch is CancellationError {
            return
        } catch {
            lastRefreshErrorDescription = error.localizedDescription
            observer.loaderFailed(typeName: typeName, url: query.url, error: error)
            // Preserve existing items if we already have some — surface the
            // error via `lastRefreshErrorDescription` only. Move to
            // `.failed` only when there's nothing to show.
            if items.isEmpty {
                state = .failed(error)
            }
        }
    }
}

// MARK: - SmartPaginatedView

/// SwiftUI `List` wrapper that auto-fires `loadMore()` when the last
/// row appears, supports pull-to-refresh, and shows a progress spinner
/// at the bottom while fetching. Drop a `PaginatedLoaderProtocol` in,
/// describe one row, get an infinite-scroll list.
public struct SmartPaginatedView<Loader: PaginatedLoaderProtocol, Row: View>: View {
    @State private var loader: Loader
    private let row: (Loader.Item) -> Row

    public init(
        loader: Loader,
        @ViewBuilder row: @escaping (Loader.Item) -> Row
    ) {
        self._loader = State(initialValue: loader)
        self.row = row
    }

    public var body: some View {
        List {
            ForEach(loader.items) { item in
                row(item)
                    .task {
                        // Last row visible → kick off the next page. The
                        // loader's own guard ensures we don't double-fire.
                        if item.id == loader.items.last?.id && loader.hasMore {
                            await loader.loadMore()
                        }
                    }
            }
            if loader.isLoadingMore {
                HStack {
                    Spacer()
                    ProgressView()
                        .accessibilityLabel("Loading more")
                    Spacer()
                }
                .listRowSeparator(.hidden)
            }
            if !loader.lastRefreshErrorDescription.isEmpty {
                Text(loader.lastRefreshErrorDescription)
                    .font(.caption)
                    .foregroundStyle(.red)
                    .listRowSeparator(.hidden)
            }
        }
        .refreshable { await loader.load() }
        .task {
            if loader.items.isEmpty { await loader.load() }
        }
    }
}
#endif
