// Mode 2: OpenAPI spec → entire API surface
// ─────────────────────────────────────────────────────────────────────
// When the API has a published OpenAPI spec, you can generate hundreds
// of typed Swift models in one command. Run it once, commit the
// generated wrappers, treat them as source.

// Workflow:
//
//   1. Get the spec (curl from the API provider, or grab a copy from
//      Stripe / GitHub / your own backend team).
//
//        $ curl https://api.stripe.com/openapi.json > stripe-spec.json
//
//   2. Run the CLI:
//
//        $ swift run smartapi-bundle openapi stripe-spec.json Sources/MyApp/Generated/
//        generated Sources/MyApp/Generated/Customer+SmartAPI.swift
//        generated Sources/MyApp/Generated/Charge+SmartAPI.swift
//        generated Sources/MyApp/Generated/PaymentIntent+SmartAPI.swift
//        ... 200+ more
//        smartapi-bundle openapi: 203 schemas imported
//
//   3. Commit the generated files. They're plain Swift; diffing
//      them in PRs shows exactly what changed when the API evolves.
//
//   4. Use them like any other @SmartAPI type:

import SwiftUI
import SmartAPI

// MARK: - What the generated files look like

// You'd never write these by hand — the CLI does. Showing one here so
// you can see what comes out the other end.
//
//     // AUTO-GENERATED by smartapi-bundle from openapi:Customer
//     // Do not edit by hand. Re-run `swift run smartapi-bundle` to refresh.
//
//     import SmartAPI
//
//     @SmartAPI(sample: #"""
//     {
//       "id": "example",
//       "email": "user@example.com",
//       "name": "example",
//       "balance": 1,
//       "created": 1
//     }
//     """#)
//     public enum Customer {}

// MARK: - Catalog the endpoints (this part you still write)

enum StripeAPI {
    static let client = SmartClient(
        defaultHeaders: ["Stripe-Version": "2024-04-10"],
        baseURL: URL(string: "https://api.stripe.com/v1")!,
        authorization: BearerTokenProvider(initialToken: ProcessInfo.processInfo.environment["STRIPE_KEY"]) {
            // For Stripe, the API key doesn't refresh — return nil to
            // give up rather than retry-loop.
            return nil
        },
        retryPolicy: .standard
    )

    // The CLI generates types named after the schema in components.schemas.
    // Here we reference them in a typed endpoint catalog.
    //
    //   static let listCustomers = SmartEndpoint<[Customer.Model]>(path: "/customers")
    //   static let getCustomer   = SmartEndpoint<Customer.Model>(path: "/customers/{id}")
    //   static let getCharge     = SmartEndpoint<Charge.Model>(path: "/charges/{id}")
}

// MARK: - Use them

// @MainActor
// func openAPIModeDemo() async throws {
//     let customer = try await StripeAPI.client.call(
//         StripeAPI.getCustomer,
//         pathParams: ["id": "cus_abc123"]
//     )
//     print(customer.email)
//     print(customer.balance)  // in cents, but typed Int
// }

// MARK: - Why this mode

// • **Scale**: 200+ schemas in one command. Hand-writing those Codables
//   would take a team a week.
//
// • **Diff-on-PR**: when the API adds a field, the next CLI run
//   shows up as a Swift diff. Reviewers see exactly what changed.
//
// • **Single source of truth**: the .smartapi.json wrappers ARE your
//   contract with the API. No drift between OpenAPI doc and code.
//
// • **Idempotent**: re-running the CLI on an unchanged spec does
//   nothing. Safe to wire into CI.
